# This file was auto-generated by Rapiddocs from our API Definition.

from ....core.exceptions.rapiddocs_http_exception import RapiddocsHTTPException
from ..types.unauthorized_request_error_body import UnauthorizedRequestErrorBody


class UnauthorizedRequest(RapiddocsHTTPException):
    def __init__(self, error: UnauthorizedRequestErrorBody):
        super().__init__(status_code=401, name="UnauthorizedRequest", content=error)
